hospitalDatabase:
  host: "b5dhnp4grxggxz9xwe8t-mysql.services.clever-cloud.com"
  port: "3306"
  user: "ujftlzqgcc1ktujb"
  password: "hT31BbJ0y08CxWEpGrf9"
  databaseName: "b5dhnp4grxggxz9xwe8t"
